# Generated by Django 3.0.5 on 2020-05-10 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mc_details',
            fields=[
                ('mc_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mc_name', models.CharField(max_length=250)),
                ('mc_address', models.CharField(max_length=700)),
                ('mc_email', models.CharField(max_length=100)),
                ('mc_main_tele', models.CharField(max_length=15)),
                ('mc_contact_person', models.CharField(max_length=100)),
                ('mc_designation', models.CharField(max_length=100)),
                ('mc_contact_person_mob', models.CharField(max_length=15)),
                ('mc_registered_date', models.DateTimeField()),
                ('mc_approved_by', models.CharField(blank=True, max_length=10, null=True)),
                ('mc_approved_on', models.DateTimeField(blank=True, null=True)),
                ('mc_num_sub_acc', models.IntegerField(blank=True, null=True)),
                ('mc_currency', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sub_bank',
            fields=[
                ('sub_bank_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sub_bank_name', models.CharField(max_length=100)),
                ('sub_bank_address', models.CharField(max_length=700)),
                ('sub_bank_tel', models.CharField(max_length=15)),
                ('sub_bank_acc', models.CharField(max_length=100)),
                ('sub_mc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BPMS.mc_details')),
            ],
        ),
        migrations.CreateModel(
            name='sub_clients',
            fields=[
                ('sub_client_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('sub_client_name', models.CharField(max_length=250)),
                ('sub_address', models.CharField(max_length=500)),
                ('sub_tele', models.CharField(max_length=15)),
                ('sub_contact_person', models.CharField(max_length=100)),
                ('sub_mc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BPMS.mc_details')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('u_user_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('u_pwd', models.CharField(max_length=500)),
                ('u_level', models.CharField(max_length=15)),
                ('u_acc_status', models.CharField(max_length=15)),
                ('u_mc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BPMS.mc_details')),
            ],
        ),
        migrations.CreateModel(
            name='sub_tax',
            fields=[
                ('sub_tax_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sub_tax_amount', models.IntegerField(default=0)),
                ('sub_tax_default', models.BooleanField()),
                ('sub_mc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BPMS.mc_details')),
            ],
        ),
        migrations.CreateModel(
            name='sub_credit_info',
            fields=[
                ('c_invoice_num', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('c_invoice_date', models.DateField()),
                ('c_description', models.TextField()),
                ('c_detail_amount', models.TextField()),
                ('c_total_amount', models.IntegerField()),
                ('c_received_amount', models.IntegerField()),
                ('c_received_date', models.DateField()),
                ('c_cheque_num', models.CharField(max_length=25)),
                ('c_remark', models.CharField(max_length=250)),
                ('c_payment_type', models.CharField(max_length=10)),
                ('c_status', models.CharField(default='open', max_length=10)),
                ('c_tax1_name', models.CharField(max_length=10)),
                ('c_tax1', models.IntegerField(default=0)),
                ('c_discount', models.IntegerField(default=0)),
                ('c_PO_num', models.CharField(max_length=100)),
                ('c_note_to_client', models.TextField()),
                ('c_mc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BPMS.mc_details')),
                ('sub_bank_id', models.ForeignKey(default='NA', on_delete=django.db.models.deletion.CASCADE, to='BPMS.sub_bank')),
                ('sub_client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BPMS.sub_clients')),
            ],
        ),
    ]
