# Generated by Django 3.0.5 on 2020-05-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_credit_info',
            name='c_due_date',
            field=models.DateField(default='1111-11-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_credit_info',
            name='c_tax_string',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
