# Generated by Django 3.0.5 on 2020-05-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPMS', '0002_auto_20200513_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_credit_info',
            name='c_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sub_credit_info',
            name='c_received_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sub_credit_info',
            name='c_tax1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sub_credit_info',
            name='c_total_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sub_tax',
            name='sub_tax_amount',
            field=models.FloatField(default=0),
        ),
    ]
