# Generated by Django 3.0.5 on 2020-05-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPMS', '0003_auto_20200514_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_details',
            name='mc_lastinvoice',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
